/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { oneOf, Schema, string, validateAndMap } from '../../schema';
import { System, systemSchema } from '../system';

/** This is a container type for one-of types. */
export type CreateMessageRequestSystem = string | System;

export const createMessageRequestSystemSchema: Schema<CreateMessageRequestSystem> = oneOf(
  [string(), systemSchema]
);

export namespace CreateMessageRequestSystem {
  /**
   * Validation method to narrow down union type to string type case.
   *
   * This is String case.
   */
  export function isString(value: unknown): value is string {
    return typeof value === 'string';
  }

  /**
   * Validation method to narrow down union type to System type case.
   *
   * This is System case.
   */
  export function isSystem(value: unknown): value is System {
    const validationResult = validateAndMap(value, systemSchema);
    return validationResult.errors === false;
  }
}
