/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, oneOf, Schema, string, validateAndMap } from '../../schema';
import { ContentRequest2, contentRequest2Schema } from './contentRequest2';

/** This is a container type for one-of types. */
export type MessageContent = string | ContentRequest2[];

export const messageContentSchema: Schema<MessageContent> = oneOf([
  string(),
  array(contentRequest2Schema),
]);

export namespace MessageContent {
  /**
   * Validation method to narrow down union type to string type case.
   *
   * This is String case.
   */
  export function isString(value: unknown): value is string {
    return typeof value === 'string';
  }

  /**
   * Validation method to narrow down union type to ContentRequest2[] type case.
   *
   * This is Array of ContentRequest case.
   */
  export function isArrayOfContentRequest2(
    value: unknown
  ): value is ContentRequest2[] {
    if (!Array.isArray(value)) {
      return false;
    }
    const validationResult = validateAndMap(
      value,
      array(contentRequest2Schema)
    );
    return validationResult.errors === false;
  }
}
