/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Error } from '../models/error';

/**
 * Creates an instance of ErrorResponse
 */
interface ErrorResponse {
  error: Error;
  type: string;
}

export class ErrorResponseError extends ApiError<ErrorResponse> {}
