/* tslint:disable */
/* eslint-disable */
/**
 * Job Portal API
 * API for the JairoJobs.com job portal MVP.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@jairojobs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobJobType } from './JobJobType';
import {
    JobJobTypeFromJSON,
    JobJobTypeFromJSONTyped,
    JobJobTypeToJSON,
    JobJobTypeToJSONTyped,
} from './JobJobType';
import type { JobRemoteOption } from './JobRemoteOption';
import {
    JobRemoteOptionFromJSON,
    JobRemoteOptionFromJSONTyped,
    JobRemoteOptionToJSON,
    JobRemoteOptionToJSONTyped,
} from './JobRemoteOption';
import type { JobExperienceLevel } from './JobExperienceLevel';
import {
    JobExperienceLevelFromJSON,
    JobExperienceLevelFromJSONTyped,
    JobExperienceLevelToJSON,
    JobExperienceLevelToJSONTyped,
} from './JobExperienceLevel';
import type { JobSalary } from './JobSalary';
import {
    JobSalaryFromJSON,
    JobSalaryFromJSONTyped,
    JobSalaryToJSON,
    JobSalaryToJSONTyped,
} from './JobSalary';

/**
 * Full details of a job listing.
 * @export
 * @interface Job
 */
export interface Job {
    /**
     * Unique identifier for the job.
     * @type {string}
     * @memberof Job
     */
    id?: string;
    /**
     * The title of the job.
     * @type {string}
     * @memberof Job
     */
    title?: string;
    /**
     * The name of the company posting the job.
     * @type {string}
     * @memberof Job
     */
    company?: string;
    /**
     * Unique identifier for the company.
     * @type {string}
     * @memberof Job
     */
    companyId?: string;
    /**
     * URL to the company's logo.
     * @type {string}
     * @memberof Job
     */
    companyLogo?: string;
    /**
     * The location of the job.
     * @type {string}
     * @memberof Job
     */
    location?: string;
    /**
     * 
     * @type {JobJobType}
     * @memberof Job
     */
    type?: JobJobType;
    /**
     * 
     * @type {JobExperienceLevel}
     * @memberof Job
     */
    experienceLevel?: JobExperienceLevel;
    /**
     * 
     * @type {JobRemoteOption}
     * @memberof Job
     */
    remoteOption?: JobRemoteOption;
    /**
     * 
     * @type {JobSalary}
     * @memberof Job
     */
    salary?: JobSalary;
    /**
     * The full description of the job.
     * @type {string}
     * @memberof Job
     */
    description?: string;
    /**
     * List of requirements for the job.
     * @type {Array<string>}
     * @memberof Job
     */
    requirements?: Array<string>;
    /**
     * List of responsibilities for the job.
     * @type {Array<string>}
     * @memberof Job
     */
    responsibilities?: Array<string>;
    /**
     * List of benefits for the job.
     * @type {Array<string>}
     * @memberof Job
     */
    benefits?: Array<string>;
    /**
     * List of tags for the job.
     * @type {Array<string>}
     * @memberof Job
     */
    tags?: Array<string>;
    /**
     * The date the job was posted.
     * @type {Date}
     * @memberof Job
     */
    postedAt?: Date;
    /**
     * The deadline for applying for the job.
     * @type {Date}
     * @memberof Job
     */
    applicationDeadline?: Date;
    /**
     * The number of applicants for the job.
     * @type {number}
     * @memberof Job
     */
    applicants?: number;
    /**
     * Whether the job is featured or not.
     * @type {boolean}
     * @memberof Job
     */
    featured?: boolean;
    /**
     * Whether the job is active or not.
     * @type {boolean}
     * @memberof Job
     */
    active?: boolean;
}



/**
 * Check if a given object implements the Job interface.
 */
export function instanceOfJob(value: object): value is Job {
    return true;
}

export function JobFromJSON(json: any): Job {
    return JobFromJSONTyped(json, false);
}

export function JobFromJSONTyped(json: any, ignoreDiscriminator: boolean): Job {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'company': json['company'] == null ? undefined : json['company'],
        'companyId': json['companyId'] == null ? undefined : json['companyId'],
        'companyLogo': json['companyLogo'] == null ? undefined : json['companyLogo'],
        'location': json['location'] == null ? undefined : json['location'],
        'type': json['type'] == null ? undefined : JobJobTypeFromJSON(json['type']),
        'experienceLevel': json['experienceLevel'] == null ? undefined : JobExperienceLevelFromJSON(json['experienceLevel']),
        'remoteOption': json['remoteOption'] == null ? undefined : JobRemoteOptionFromJSON(json['remoteOption']),
        'salary': json['salary'] == null ? undefined : JobSalaryFromJSON(json['salary']),
        'description': json['description'] == null ? undefined : json['description'],
        'requirements': json['requirements'] == null ? undefined : json['requirements'],
        'responsibilities': json['responsibilities'] == null ? undefined : json['responsibilities'],
        'benefits': json['benefits'] == null ? undefined : json['benefits'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'postedAt': json['postedAt'] == null ? undefined : (new Date(json['postedAt'])),
        'applicationDeadline': json['applicationDeadline'] == null ? undefined : (new Date(json['applicationDeadline'])),
        'applicants': json['applicants'] == null ? undefined : json['applicants'],
        'featured': json['featured'] == null ? undefined : json['featured'],
        'active': json['active'] == null ? undefined : json['active'],
    };
}

export function JobToJSON(json: any): Job {
    return JobToJSONTyped(json, false);
}

export function JobToJSONTyped(value?: Job | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'company': value['company'],
        'companyId': value['companyId'],
        'companyLogo': value['companyLogo'],
        'location': value['location'],
        'type': JobJobTypeToJSON(value['type']),
        'experienceLevel': JobExperienceLevelToJSON(value['experienceLevel']),
        'remoteOption': JobRemoteOptionToJSON(value['remoteOption']),
        'salary': JobSalaryToJSON(value['salary']),
        'description': value['description'],
        'requirements': value['requirements'],
        'responsibilities': value['responsibilities'],
        'benefits': value['benefits'],
        'tags': value['tags'],
        'postedAt': value['postedAt'] == null ? undefined : ((value['postedAt']).toISOString()),
        'applicationDeadline': value['applicationDeadline'] == null ? undefined : ((value['applicationDeadline']).toISOString()),
        'applicants': value['applicants'],
        'featured': value['featured'],
        'active': value['active'],
    };
}

