"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Job Portal API
 * API for the JairoJobs.com job portal MVP.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@jairojobs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfJob = instanceOfJob;
exports.JobFromJSON = JobFromJSON;
exports.JobFromJSONTyped = JobFromJSONTyped;
exports.JobToJSON = JobToJSON;
exports.JobToJSONTyped = JobToJSONTyped;
const JobJobType_1 = require("./JobJobType");
const JobRemoteOption_1 = require("./JobRemoteOption");
const JobExperienceLevel_1 = require("./JobExperienceLevel");
const JobSalary_1 = require("./JobSalary");
/**
 * Check if a given object implements the Job interface.
 */
function instanceOfJob(value) {
    return true;
}
function JobFromJSON(json) {
    return JobFromJSONTyped(json, false);
}
function JobFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'company': json['company'] == null ? undefined : json['company'],
        'companyId': json['companyId'] == null ? undefined : json['companyId'],
        'companyLogo': json['companyLogo'] == null ? undefined : json['companyLogo'],
        'location': json['location'] == null ? undefined : json['location'],
        'type': json['type'] == null ? undefined : (0, JobJobType_1.JobJobTypeFromJSON)(json['type']),
        'experienceLevel': json['experienceLevel'] == null ? undefined : (0, JobExperienceLevel_1.JobExperienceLevelFromJSON)(json['experienceLevel']),
        'remoteOption': json['remoteOption'] == null ? undefined : (0, JobRemoteOption_1.JobRemoteOptionFromJSON)(json['remoteOption']),
        'salary': json['salary'] == null ? undefined : (0, JobSalary_1.JobSalaryFromJSON)(json['salary']),
        'description': json['description'] == null ? undefined : json['description'],
        'requirements': json['requirements'] == null ? undefined : json['requirements'],
        'responsibilities': json['responsibilities'] == null ? undefined : json['responsibilities'],
        'benefits': json['benefits'] == null ? undefined : json['benefits'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'postedAt': json['postedAt'] == null ? undefined : (new Date(json['postedAt'])),
        'applicationDeadline': json['applicationDeadline'] == null ? undefined : (new Date(json['applicationDeadline'])),
        'applicants': json['applicants'] == null ? undefined : json['applicants'],
        'featured': json['featured'] == null ? undefined : json['featured'],
        'active': json['active'] == null ? undefined : json['active'],
    };
}
function JobToJSON(json) {
    return JobToJSONTyped(json, false);
}
function JobToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'title': value['title'],
        'company': value['company'],
        'companyId': value['companyId'],
        'companyLogo': value['companyLogo'],
        'location': value['location'],
        'type': (0, JobJobType_1.JobJobTypeToJSON)(value['type']),
        'experienceLevel': (0, JobExperienceLevel_1.JobExperienceLevelToJSON)(value['experienceLevel']),
        'remoteOption': (0, JobRemoteOption_1.JobRemoteOptionToJSON)(value['remoteOption']),
        'salary': (0, JobSalary_1.JobSalaryToJSON)(value['salary']),
        'description': value['description'],
        'requirements': value['requirements'],
        'responsibilities': value['responsibilities'],
        'benefits': value['benefits'],
        'tags': value['tags'],
        'postedAt': value['postedAt'] == null ? undefined : ((value['postedAt']).toISOString()),
        'applicationDeadline': value['applicationDeadline'] == null ? undefined : ((value['applicationDeadline']).toISOString()),
        'applicants': value['applicants'],
        'featured': value['featured'],
        'active': value['active'],
    };
}
