"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Job Portal API
 * API for the JairoJobs.com job portal MVP.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@jairojobs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.JobExperienceLevel = void 0;
exports.instanceOfJobExperienceLevel = instanceOfJobExperienceLevel;
exports.JobExperienceLevelFromJSON = JobExperienceLevelFromJSON;
exports.JobExperienceLevelFromJSONTyped = JobExperienceLevelFromJSONTyped;
exports.JobExperienceLevelToJSON = JobExperienceLevelToJSON;
exports.JobExperienceLevelToJSONTyped = JobExperienceLevelToJSONTyped;
/**
 * The required experience level.
 * @export
 */
exports.JobExperienceLevel = {
    Entry: 'entry',
    Mid: 'mid',
    Senior: 'senior'
};
function instanceOfJobExperienceLevel(value) {
    for (const key in exports.JobExperienceLevel) {
        if (Object.prototype.hasOwnProperty.call(exports.JobExperienceLevel, key)) {
            if (exports.JobExperienceLevel[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function JobExperienceLevelFromJSON(json) {
    return JobExperienceLevelFromJSONTyped(json, false);
}
function JobExperienceLevelFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function JobExperienceLevelToJSON(value) {
    return value;
}
function JobExperienceLevelToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
