/* tslint:disable */
/* eslint-disable */
/**
 * Job Portal API
 * API for the JairoJobs.com job portal MVP.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@jairojobs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The required experience level.
 * @export
 */
export const JobExperienceLevel = {
    Entry: 'entry',
    Mid: 'mid',
    Senior: 'senior'
} as const;
export type JobExperienceLevel = typeof JobExperienceLevel[keyof typeof JobExperienceLevel];


export function instanceOfJobExperienceLevel(value: any): boolean {
    for (const key in JobExperienceLevel) {
        if (Object.prototype.hasOwnProperty.call(JobExperienceLevel, key)) {
            if (JobExperienceLevel[key as keyof typeof JobExperienceLevel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobExperienceLevelFromJSON(json: any): JobExperienceLevel {
    return JobExperienceLevelFromJSONTyped(json, false);
}

export function JobExperienceLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobExperienceLevel {
    return json as JobExperienceLevel;
}

export function JobExperienceLevelToJSON(value?: JobExperienceLevel | null): any {
    return value as any;
}

export function JobExperienceLevelToJSONTyped(value: any, ignoreDiscriminator: boolean): JobExperienceLevel {
    return value as JobExperienceLevel;
}

