/* tslint:disable */
/* eslint-disable */
/**
 * Job Portal API
 * API for the JairoJobs.com job portal MVP.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@jairojobs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The type of employment.
 * @export
 */
export const JobJobType = {
    FullTime: 'full-time',
    PartTime: 'part-time',
    Contract: 'contract',
    Internship: 'internship'
} as const;
export type JobJobType = typeof JobJobType[keyof typeof JobJobType];


export function instanceOfJobJobType(value: any): boolean {
    for (const key in JobJobType) {
        if (Object.prototype.hasOwnProperty.call(JobJobType, key)) {
            if (JobJobType[key as keyof typeof JobJobType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobJobTypeFromJSON(json: any): JobJobType {
    return JobJobTypeFromJSONTyped(json, false);
}

export function JobJobTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobJobType {
    return json as JobJobType;
}

export function JobJobTypeToJSON(value?: JobJobType | null): any {
    return value as any;
}

export function JobJobTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): JobJobType {
    return value as JobJobType;
}

