"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Job Portal API
 * API for the JairoJobs.com job portal MVP.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@jairojobs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.JobJobType = void 0;
exports.instanceOfJobJobType = instanceOfJobJobType;
exports.JobJobTypeFromJSON = JobJobTypeFromJSON;
exports.JobJobTypeFromJSONTyped = JobJobTypeFromJSONTyped;
exports.JobJobTypeToJSON = JobJobTypeToJSON;
exports.JobJobTypeToJSONTyped = JobJobTypeToJSONTyped;
/**
 * The type of employment.
 * @export
 */
exports.JobJobType = {
    FullTime: 'full-time',
    PartTime: 'part-time',
    Contract: 'contract',
    Internship: 'internship'
};
function instanceOfJobJobType(value) {
    for (const key in exports.JobJobType) {
        if (Object.prototype.hasOwnProperty.call(exports.JobJobType, key)) {
            if (exports.JobJobType[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function JobJobTypeFromJSON(json) {
    return JobJobTypeFromJSONTyped(json, false);
}
function JobJobTypeFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function JobJobTypeToJSON(value) {
    return value;
}
function JobJobTypeToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
