/* tslint:disable */
/* eslint-disable */
/**
 * Job Portal API
 * API for the JairoJobs.com job portal MVP.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@jairojobs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The remote work option.
 * @export
 */
export const JobRemoteOption = {
    OnSite: 'on-site',
    Hybrid: 'hybrid',
    Remote: 'remote'
} as const;
export type JobRemoteOption = typeof JobRemoteOption[keyof typeof JobRemoteOption];


export function instanceOfJobRemoteOption(value: any): boolean {
    for (const key in JobRemoteOption) {
        if (Object.prototype.hasOwnProperty.call(JobRemoteOption, key)) {
            if (JobRemoteOption[key as keyof typeof JobRemoteOption] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobRemoteOptionFromJSON(json: any): JobRemoteOption {
    return JobRemoteOptionFromJSONTyped(json, false);
}

export function JobRemoteOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobRemoteOption {
    return json as JobRemoteOption;
}

export function JobRemoteOptionToJSON(value?: JobRemoteOption | null): any {
    return value as any;
}

export function JobRemoteOptionToJSONTyped(value: any, ignoreDiscriminator: boolean): JobRemoteOption {
    return value as JobRemoteOption;
}

