"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Job Portal API
 * API for the JairoJobs.com job portal MVP.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@jairojobs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.JobRemoteOption = void 0;
exports.instanceOfJobRemoteOption = instanceOfJobRemoteOption;
exports.JobRemoteOptionFromJSON = JobRemoteOptionFromJSON;
exports.JobRemoteOptionFromJSONTyped = JobRemoteOptionFromJSONTyped;
exports.JobRemoteOptionToJSON = JobRemoteOptionToJSON;
exports.JobRemoteOptionToJSONTyped = JobRemoteOptionToJSONTyped;
/**
 * The remote work option.
 * @export
 */
exports.JobRemoteOption = {
    OnSite: 'on-site',
    Hybrid: 'hybrid',
    Remote: 'remote'
};
function instanceOfJobRemoteOption(value) {
    for (const key in exports.JobRemoteOption) {
        if (Object.prototype.hasOwnProperty.call(exports.JobRemoteOption, key)) {
            if (exports.JobRemoteOption[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function JobRemoteOptionFromJSON(json) {
    return JobRemoteOptionFromJSONTyped(json, false);
}
function JobRemoteOptionFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function JobRemoteOptionToJSON(value) {
    return value;
}
function JobRemoteOptionToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
