/* tslint:disable */
/* eslint-disable */
/**
 * Job Portal API
 * API for the JairoJobs.com job portal MVP.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@jairojobs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The remote work option.
 * @export
 */
export const JobSummaryRemoteOption = {
    OnSite: 'on-site',
    Hybrid: 'hybrid',
    Remote: 'remote'
} as const;
export type JobSummaryRemoteOption = typeof JobSummaryRemoteOption[keyof typeof JobSummaryRemoteOption];


export function instanceOfJobSummaryRemoteOption(value: any): boolean {
    for (const key in JobSummaryRemoteOption) {
        if (Object.prototype.hasOwnProperty.call(JobSummaryRemoteOption, key)) {
            if (JobSummaryRemoteOption[key as keyof typeof JobSummaryRemoteOption] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobSummaryRemoteOptionFromJSON(json: any): JobSummaryRemoteOption {
    return JobSummaryRemoteOptionFromJSONTyped(json, false);
}

export function JobSummaryRemoteOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobSummaryRemoteOption {
    return json as JobSummaryRemoteOption;
}

export function JobSummaryRemoteOptionToJSON(value?: JobSummaryRemoteOption | null): any {
    return value as any;
}

export function JobSummaryRemoteOptionToJSONTyped(value: any, ignoreDiscriminator: boolean): JobSummaryRemoteOption {
    return value as JobSummaryRemoteOption;
}

