/* tslint:disable */
/* eslint-disable */
/**
 * Job Portal API
 * API for the JairoJobs.com job portal MVP.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@jairojobs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobSummaryRemoteOption } from './JobSummaryRemoteOption';
import {
    JobSummaryRemoteOptionFromJSON,
    JobSummaryRemoteOptionFromJSONTyped,
    JobSummaryRemoteOptionToJSON,
    JobSummaryRemoteOptionToJSONTyped,
} from './JobSummaryRemoteOption';
import type { JobSummaryJobType } from './JobSummaryJobType';
import {
    JobSummaryJobTypeFromJSON,
    JobSummaryJobTypeFromJSONTyped,
    JobSummaryJobTypeToJSON,
    JobSummaryJobTypeToJSONTyped,
} from './JobSummaryJobType';

/**
 * A summary of a job listing.
 * @export
 * @interface JobSummary
 */
export interface JobSummary {
    /**
     * Unique identifier for the job.
     * @type {string}
     * @memberof JobSummary
     */
    id?: string;
    /**
     * The title of the job.
     * @type {string}
     * @memberof JobSummary
     */
    title?: string;
    /**
     * The name of the company posting the job.
     * @type {string}
     * @memberof JobSummary
     */
    company?: string;
    /**
     * The location of the job.
     * @type {string}
     * @memberof JobSummary
     */
    location?: string;
    /**
     * 
     * @type {JobSummaryJobType}
     * @memberof JobSummary
     */
    type?: JobSummaryJobType;
    /**
     * 
     * @type {JobSummaryRemoteOption}
     * @memberof JobSummary
     */
    remoteOption?: JobSummaryRemoteOption;
    /**
     * The date the job was posted.
     * @type {Date}
     * @memberof JobSummary
     */
    postedAt?: Date;
}



/**
 * Check if a given object implements the JobSummary interface.
 */
export function instanceOfJobSummary(value: object): value is JobSummary {
    return true;
}

export function JobSummaryFromJSON(json: any): JobSummary {
    return JobSummaryFromJSONTyped(json, false);
}

export function JobSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'company': json['company'] == null ? undefined : json['company'],
        'location': json['location'] == null ? undefined : json['location'],
        'type': json['type'] == null ? undefined : JobSummaryJobTypeFromJSON(json['type']),
        'remoteOption': json['remoteOption'] == null ? undefined : JobSummaryRemoteOptionFromJSON(json['remoteOption']),
        'postedAt': json['postedAt'] == null ? undefined : (new Date(json['postedAt'])),
    };
}

export function JobSummaryToJSON(json: any): JobSummary {
    return JobSummaryToJSONTyped(json, false);
}

export function JobSummaryToJSONTyped(value?: JobSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'company': value['company'],
        'location': value['location'],
        'type': JobSummaryJobTypeToJSON(value['type']),
        'remoteOption': JobSummaryRemoteOptionToJSON(value['remoteOption']),
        'postedAt': value['postedAt'] == null ? undefined : ((value['postedAt']).toISOString()),
    };
}

