"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Job Portal API
 * API for the JairoJobs.com job portal MVP.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@jairojobs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfJobSummary = instanceOfJobSummary;
exports.JobSummaryFromJSON = JobSummaryFromJSON;
exports.JobSummaryFromJSONTyped = JobSummaryFromJSONTyped;
exports.JobSummaryToJSON = JobSummaryToJSON;
exports.JobSummaryToJSONTyped = JobSummaryToJSONTyped;
const JobSummaryRemoteOption_1 = require("./JobSummaryRemoteOption");
const JobSummaryJobType_1 = require("./JobSummaryJobType");
/**
 * Check if a given object implements the JobSummary interface.
 */
function instanceOfJobSummary(value) {
    return true;
}
function JobSummaryFromJSON(json) {
    return JobSummaryFromJSONTyped(json, false);
}
function JobSummaryFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'company': json['company'] == null ? undefined : json['company'],
        'location': json['location'] == null ? undefined : json['location'],
        'type': json['type'] == null ? undefined : (0, JobSummaryJobType_1.JobSummaryJobTypeFromJSON)(json['type']),
        'remoteOption': json['remoteOption'] == null ? undefined : (0, JobSummaryRemoteOption_1.JobSummaryRemoteOptionFromJSON)(json['remoteOption']),
        'postedAt': json['postedAt'] == null ? undefined : (new Date(json['postedAt'])),
    };
}
function JobSummaryToJSON(json) {
    return JobSummaryToJSONTyped(json, false);
}
function JobSummaryToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'title': value['title'],
        'company': value['company'],
        'location': value['location'],
        'type': (0, JobSummaryJobType_1.JobSummaryJobTypeToJSON)(value['type']),
        'remoteOption': (0, JobSummaryRemoteOption_1.JobSummaryRemoteOptionToJSON)(value['remoteOption']),
        'postedAt': value['postedAt'] == null ? undefined : ((value['postedAt']).toISOString()),
    };
}
