"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Job Portal API
 * API for the JairoJobs.com job portal MVP.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@jairojobs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.JobSummaryJobType = void 0;
exports.instanceOfJobSummaryJobType = instanceOfJobSummaryJobType;
exports.JobSummaryJobTypeFromJSON = JobSummaryJobTypeFromJSON;
exports.JobSummaryJobTypeFromJSONTyped = JobSummaryJobTypeFromJSONTyped;
exports.JobSummaryJobTypeToJSON = JobSummaryJobTypeToJSON;
exports.JobSummaryJobTypeToJSONTyped = JobSummaryJobTypeToJSONTyped;
/**
 * The type of employment.
 * @export
 */
exports.JobSummaryJobType = {
    FullTime: 'full-time',
    PartTime: 'part-time',
    Contract: 'contract',
    Internship: 'internship'
};
function instanceOfJobSummaryJobType(value) {
    for (const key in exports.JobSummaryJobType) {
        if (Object.prototype.hasOwnProperty.call(exports.JobSummaryJobType, key)) {
            if (exports.JobSummaryJobType[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function JobSummaryJobTypeFromJSON(json) {
    return JobSummaryJobTypeFromJSONTyped(json, false);
}
function JobSummaryJobTypeFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function JobSummaryJobTypeToJSON(value) {
    return value;
}
function JobSummaryJobTypeToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
