/* tslint:disable */
/* eslint-disable */
/**
 * Job Portal API
 * API for the JairoJobs.com job portal MVP.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@jairojobs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Salary information for a job.
 * @export
 * @interface JobSalary
 */
export interface JobSalary {
    /**
     * Minimum salary for the job.
     * @type {number}
     * @memberof JobSalary
     */
    min?: number;
    /**
     * Maximum salary for the job.
     * @type {number}
     * @memberof JobSalary
     */
    max?: number;
    /**
     * The currency of the salary.
     * @type {string}
     * @memberof JobSalary
     */
    currency?: string;
    /**
     * The period of the salary.
     * @type {string}
     * @memberof JobSalary
     */
    period?: string;
}

/**
 * Check if a given object implements the JobSalary interface.
 */
export function instanceOfJobSalary(value: object): value is JobSalary {
    return true;
}

export function JobSalaryFromJSON(json: any): JobSalary {
    return JobSalaryFromJSONTyped(json, false);
}

export function JobSalaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobSalary {
    if (json == null) {
        return json;
    }
    return {
        
        'min': json['min'] == null ? undefined : json['min'],
        'max': json['max'] == null ? undefined : json['max'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'period': json['period'] == null ? undefined : json['period'],
    };
}

export function JobSalaryToJSON(json: any): JobSalary {
    return JobSalaryToJSONTyped(json, false);
}

export function JobSalaryToJSONTyped(value?: JobSalary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'min': value['min'],
        'max': value['max'],
        'currency': value['currency'],
        'period': value['period'],
    };
}

