"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Job Portal API
 * API for the JairoJobs.com job portal MVP.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@jairojobs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfJobSalary = instanceOfJobSalary;
exports.JobSalaryFromJSON = JobSalaryFromJSON;
exports.JobSalaryFromJSONTyped = JobSalaryFromJSONTyped;
exports.JobSalaryToJSON = JobSalaryToJSON;
exports.JobSalaryToJSONTyped = JobSalaryToJSONTyped;
/**
 * Check if a given object implements the JobSalary interface.
 */
function instanceOfJobSalary(value) {
    return true;
}
function JobSalaryFromJSON(json) {
    return JobSalaryFromJSONTyped(json, false);
}
function JobSalaryFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'min': json['min'] == null ? undefined : json['min'],
        'max': json['max'] == null ? undefined : json['max'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'period': json['period'] == null ? undefined : json['period'],
    };
}
function JobSalaryToJSON(json) {
    return JobSalaryToJSONTyped(json, false);
}
function JobSalaryToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'min': value['min'],
        'max': value['max'],
        'currency': value['currency'],
        'period': value['period'],
    };
}
