/* tslint:disable */
/* eslint-disable */
/**
 * Job Portal API
 * API for the JairoJobs.com job portal MVP.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@jairojobs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The type of employment.
 * @export
 */
export const JobSummaryJobType = {
    FullTime: 'full-time',
    PartTime: 'part-time',
    Contract: 'contract',
    Internship: 'internship'
} as const;
export type JobSummaryJobType = typeof JobSummaryJobType[keyof typeof JobSummaryJobType];


export function instanceOfJobSummaryJobType(value: any): boolean {
    for (const key in JobSummaryJobType) {
        if (Object.prototype.hasOwnProperty.call(JobSummaryJobType, key)) {
            if (JobSummaryJobType[key as keyof typeof JobSummaryJobType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobSummaryJobTypeFromJSON(json: any): JobSummaryJobType {
    return JobSummaryJobTypeFromJSONTyped(json, false);
}

export function JobSummaryJobTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobSummaryJobType {
    return json as JobSummaryJobType;
}

export function JobSummaryJobTypeToJSON(value?: JobSummaryJobType | null): any {
    return value as any;
}

export function JobSummaryJobTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): JobSummaryJobType {
    return value as JobSummaryJobType;
}

