"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Job Portal API
 * API for the JairoJobs.com job portal MVP.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@jairojobs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.JobSummaryRemoteOption = void 0;
exports.instanceOfJobSummaryRemoteOption = instanceOfJobSummaryRemoteOption;
exports.JobSummaryRemoteOptionFromJSON = JobSummaryRemoteOptionFromJSON;
exports.JobSummaryRemoteOptionFromJSONTyped = JobSummaryRemoteOptionFromJSONTyped;
exports.JobSummaryRemoteOptionToJSON = JobSummaryRemoteOptionToJSON;
exports.JobSummaryRemoteOptionToJSONTyped = JobSummaryRemoteOptionToJSONTyped;
/**
 * The remote work option.
 * @export
 */
exports.JobSummaryRemoteOption = {
    OnSite: 'on-site',
    Hybrid: 'hybrid',
    Remote: 'remote'
};
function instanceOfJobSummaryRemoteOption(value) {
    for (const key in exports.JobSummaryRemoteOption) {
        if (Object.prototype.hasOwnProperty.call(exports.JobSummaryRemoteOption, key)) {
            if (exports.JobSummaryRemoteOption[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function JobSummaryRemoteOptionFromJSON(json) {
    return JobSummaryRemoteOptionFromJSONTyped(json, false);
}
function JobSummaryRemoteOptionFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function JobSummaryRemoteOptionToJSON(value) {
    return value;
}
function JobSummaryRemoteOptionToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
