"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Job Portal API
 * API for the JairoJobs.com job portal MVP.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@jairojobs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfPagination = instanceOfPagination;
exports.PaginationFromJSON = PaginationFromJSON;
exports.PaginationFromJSONTyped = PaginationFromJSONTyped;
exports.PaginationToJSON = PaginationToJSON;
exports.PaginationToJSONTyped = PaginationToJSONTyped;
/**
 * Check if a given object implements the Pagination interface.
 */
function instanceOfPagination(value) {
    return true;
}
function PaginationFromJSON(json) {
    return PaginationFromJSONTyped(json, false);
}
function PaginationFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'total': json['total'] == null ? undefined : json['total'],
        'page': json['page'] == null ? undefined : json['page'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}
function PaginationToJSON(json) {
    return PaginationToJSONTyped(json, false);
}
function PaginationToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'total': value['total'],
        'page': value['page'],
        'limit': value['limit'],
        'totalPages': value['totalPages'],
    };
}
