"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * Job Portal API
 * API for the JairoJobs.com job portal MVP.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@jairojobs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfSearchAndListJobsResponse200Json = instanceOfSearchAndListJobsResponse200Json;
exports.SearchAndListJobsResponse200JsonFromJSON = SearchAndListJobsResponse200JsonFromJSON;
exports.SearchAndListJobsResponse200JsonFromJSONTyped = SearchAndListJobsResponse200JsonFromJSONTyped;
exports.SearchAndListJobsResponse200JsonToJSON = SearchAndListJobsResponse200JsonToJSON;
exports.SearchAndListJobsResponse200JsonToJSONTyped = SearchAndListJobsResponse200JsonToJSONTyped;
const JobSummary_1 = require("./JobSummary");
const Pagination_1 = require("./Pagination");
/**
 * Check if a given object implements the SearchAndListJobsResponse200Json interface.
 */
function instanceOfSearchAndListJobsResponse200Json(value) {
    return true;
}
function SearchAndListJobsResponse200JsonFromJSON(json) {
    return SearchAndListJobsResponse200JsonFromJSONTyped(json, false);
}
function SearchAndListJobsResponse200JsonFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'jobs': json['jobs'] == null ? undefined : (json['jobs'].map(JobSummary_1.JobSummaryFromJSON)),
        'pagination': json['pagination'] == null ? undefined : (0, Pagination_1.PaginationFromJSON)(json['pagination']),
    };
}
function SearchAndListJobsResponse200JsonToJSON(json) {
    return SearchAndListJobsResponse200JsonToJSONTyped(json, false);
}
function SearchAndListJobsResponse200JsonToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'jobs': value['jobs'] == null ? undefined : (value['jobs'].map(JobSummary_1.JobSummaryToJSON)),
        'pagination': (0, Pagination_1.PaginationToJSON)(value['pagination']),
    };
}
