/* tslint:disable */
/* eslint-disable */
/**
 * Job Portal API
 * API for the JairoJobs.com job portal MVP.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@jairojobs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobSummary } from './JobSummary';
import {
    JobSummaryFromJSON,
    JobSummaryFromJSONTyped,
    JobSummaryToJSON,
    JobSummaryToJSONTyped,
} from './JobSummary';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';

/**
 * Response schema for searching and listing jobs.
 * @export
 * @interface SearchAndListJobsResponse200Json
 */
export interface SearchAndListJobsResponse200Json {
    /**
     * A list of job summaries.
     * @type {Array<JobSummary>}
     * @memberof SearchAndListJobsResponse200Json
     */
    jobs?: Array<JobSummary>;
    /**
     * 
     * @type {Pagination}
     * @memberof SearchAndListJobsResponse200Json
     */
    pagination?: Pagination;
}

/**
 * Check if a given object implements the SearchAndListJobsResponse200Json interface.
 */
export function instanceOfSearchAndListJobsResponse200Json(value: object): value is SearchAndListJobsResponse200Json {
    return true;
}

export function SearchAndListJobsResponse200JsonFromJSON(json: any): SearchAndListJobsResponse200Json {
    return SearchAndListJobsResponse200JsonFromJSONTyped(json, false);
}

export function SearchAndListJobsResponse200JsonFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchAndListJobsResponse200Json {
    if (json == null) {
        return json;
    }
    return {
        
        'jobs': json['jobs'] == null ? undefined : ((json['jobs'] as Array<any>).map(JobSummaryFromJSON)),
        'pagination': json['pagination'] == null ? undefined : PaginationFromJSON(json['pagination']),
    };
}

export function SearchAndListJobsResponse200JsonToJSON(json: any): SearchAndListJobsResponse200Json {
    return SearchAndListJobsResponse200JsonToJSONTyped(json, false);
}

export function SearchAndListJobsResponse200JsonToJSONTyped(value?: SearchAndListJobsResponse200Json | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobs': value['jobs'] == null ? undefined : ((value['jobs'] as Array<any>).map(JobSummaryToJSON)),
        'pagination': PaginationToJSON(value['pagination']),
    };
}

