/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  CreateTextCompletionRequest,
  createTextCompletionRequestSchema,
} from '../models/createTextCompletionRequest';
import {
  CreateTextCompletionResponse,
  createTextCompletionResponseSchema,
} from '../models/createTextCompletionResponse';
import { string } from '../schema';
import { BaseController } from './baseController';
import { ErrorResponseError } from '../errors/errorResponseError';

export class TextCompletionsController extends BaseController {
  /**
   * @param anthropicVersion  The version of the Anthropic API you want to use.
   * @param body
   * @return Response from the API call
   */
  async createTextCompletion(
    anthropicVersion: string,
    body: CreateTextCompletionRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CreateTextCompletionResponse>> {
    const req = this.createRequest('POST', '/complete');
    const mapped = req.prepareArgs({
      anthropicVersion: [anthropicVersion, string()],
      body: [body, createTextCompletionRequestSchema],
    });
    req.header('anthropic-version', mapped.anthropicVersion);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ErrorResponseError, 'Error response');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(createTextCompletionResponseSchema, requestOptions);
  }
}
