/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema } from '../schema';
import { Type1Enum, type1EnumSchema } from './type1Enum';

export interface CacheControl {
  type: Type1Enum;
}

export const cacheControlSchema: Schema<CacheControl> = object({
  type: ['type', type1EnumSchema],
});
