/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string, unknown } from '../schema';
import { TypeEnum, typeEnumSchema } from './typeEnum';

export interface Content {
  /** The text content. */
  text?: string;
  /** The type of content. */
  type?: TypeEnum;
  id?: string;
  name?: string;
  input?: unknown;
}

export const contentSchema: Schema<Content> = object({
  text: ['text', optional(string())],
  type: ['type', optional(typeEnumSchema)],
  id: ['id', optional(string())],
  name: ['name', optional(string())],
  input: ['input', optional(unknown())],
});
