/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, Schema, string } from '../schema';
import { StopReason1Enum, stopReason1EnumSchema } from './stopReason1Enum';
import { Type16Enum, type16EnumSchema } from './type16Enum';

export interface CreateTextCompletionResponse {
  /**
   * Object type.
   * For Text Completions, this is always `completion`.
   */
  type: Type16Enum;
  /**
   * Unique object identifier.
   *  The format and length of IDs may change over time.
   */
  id: string;
  /** The resulting completion up to and excluding the stop sequences. */
  completion: string;
  /**
   * The reason that we stopped.
   * This may be one the following values:
   *  `stop_sequence`: we reached a stop sequence — either provided by you via the stop_sequences parameter, or a stop sequence built into the model
   * `max_tokens`: we exceeded max_tokens_to_sample or the model's maximum
   */
  stopReason: StopReason1Enum | null;
  /** The model that handled the request. */
  model: string;
}

export const createTextCompletionResponseSchema: Schema<CreateTextCompletionResponse> = object(
  {
    type: ['type', type16EnumSchema],
    id: ['id', string()],
    completion: ['completion', string()],
    stopReason: ['stop_reason', nullable(stopReason1EnumSchema)],
    model: ['model', string()],
  }
);
