/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Error {
  message?: string;
  type?: string;
}

export const errorSchema: Schema<Error> = object({
  message: ['message', optional(string())],
  type: ['type', optional(string())],
});
