/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, object, optional, Schema } from '../schema';
import { CacheControl, cacheControlSchema } from './cacheControl';
import { Source, sourceSchema } from './source';
import { Type3Enum, type3EnumSchema } from './type3Enum';

export interface ImageContent {
  /** The image source */
  source: Source;
  /** The type of content. */
  type: Type3Enum;
  cacheControl?: CacheControl | null;
}

export const imageContentSchema: Schema<ImageContent> = object({
  source: ['source', lazy(() => sourceSchema)],
  type: ['type', type3EnumSchema],
  cacheControl: [
    'cache_control',
    optional(nullable(lazy(() => cacheControlSchema))),
  ],
});
