/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, unknown } from '../schema';
import { Type11Enum, type11EnumSchema } from './type11Enum';

export interface InputSchema {
  type: Type11Enum;
  properties?: unknown | null;
}

export const inputSchemaSchema: Schema<InputSchema> = object({
  type: ['type', type11EnumSchema],
  properties: ['properties', optional(nullable(unknown()))],
});
