/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MediaTypeEnum
 */
export enum MediaTypeEnum {
  EnumImagejpeg = 'image/jpeg',
  EnumImagepng = 'image/png',
  EnumImagegif = 'image/gif',
  EnumImagewebp = 'image/webp',
}

/**
 * Schema for MediaTypeEnum
 */
export const mediaTypeEnumSchema: Schema<MediaTypeEnum> = stringEnum(
  MediaTypeEnum
);
