/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

/** An object describing metadata about the request. */
export interface Metadata {
  /**
   * An external identifier for the user who is associated with the request.
   *  This should be a uuid, hash value, or other opaque identifier. Anthropic may use this id to help detect abuse. Do not include any identifying information such as name, email address, or phone number.
   */
  userId?: string | null;
}

export const metadataSchema: Schema<Metadata> = object({
  userId: ['user_id', optional(nullable(string()))],
});
