/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import { MediaTypeEnum, mediaTypeEnumSchema } from './mediaTypeEnum';
import { Type2Enum, type2EnumSchema } from './type2Enum';

/** The image source */
export interface Source {
  type: Type2Enum;
  mediaType: MediaTypeEnum;
  data: string;
}

export const sourceSchema: Schema<Source> = object({
  type: ['type', type2EnumSchema],
  mediaType: ['media_type', mediaTypeEnumSchema],
  data: ['data', string()],
});
