/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for StopReasonEnum
 */
export enum StopReasonEnum {
  EndTurn = 'end_turn',
  MaxTokens = 'max_tokens',
  StopSequence = 'stop_sequence',
  ToolUse = 'tool_use',
}

/**
 * Schema for StopReasonEnum
 */
export const stopReasonEnumSchema: Schema<StopReasonEnum> = stringEnum(
  StopReasonEnum
);
