/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for StopReason1Enum
 */
export enum StopReason1Enum {
  MaxTokens = 'max_tokens',
  StopSequence = 'stop_sequence',
}

/**
 * Schema for StopReason1Enum
 */
export const stopReason1EnumSchema: Schema<StopReason1Enum> = stringEnum(
  StopReason1Enum
);
