/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, object, optional, Schema } from '../schema';
import { CacheControl, cacheControlSchema } from './cacheControl';

export interface System {
  cacheControl?: CacheControl | null;
}

export const systemSchema: Schema<System> = object({
  cacheControl: [
    'cache_control',
    optional(nullable(lazy(() => cacheControlSchema))),
  ],
});
