/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, object, optional, Schema, string } from '../schema';
import { CacheControl, cacheControlSchema } from './cacheControl';
import { TypeEnum, typeEnumSchema } from './typeEnum';

export interface TextContent {
  /** The text content. */
  text: string;
  /** The type of content. */
  type: TypeEnum;
  cacheControl?: CacheControl | null;
}

export const textContentSchema: Schema<TextContent> = object({
  text: ['text', string()],
  type: ['type', typeEnumSchema],
  cacheControl: [
    'cache_control',
    optional(nullable(lazy(() => cacheControlSchema))),
  ],
});
