/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import { TypeEnum, typeEnumSchema } from './typeEnum';

export interface TextContentResponse {
  /** The text content. */
  text: string;
  /** The type of content. */
  type: TypeEnum;
}

export const textContentResponseSchema: Schema<TextContentResponse> = object({
  text: ['text', string()],
  type: ['type', typeEnumSchema],
});
