/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { CacheControl, cacheControlSchema } from './cacheControl';
import { Type4Enum, type4EnumSchema } from './type4Enum';

export interface ToolUseContent {
  type: Type4Enum;
  id: string;
  name: string;
  input?: unknown;
  cacheControl?: CacheControl | null;
}

export const toolUseContentSchema: Schema<ToolUseContent> = object({
  type: ['type', type4EnumSchema],
  id: ['id', string()],
  name: ['name', string()],
  input: ['input', optional(unknown())],
  cacheControl: [
    'cache_control',
    optional(nullable(lazy(() => cacheControlSchema))),
  ],
});
