/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema } from '../schema';
import { Type8Enum, type8EnumSchema } from './type8Enum';

export interface ToolChoiceAuto {
  type: Type8Enum;
}

export const toolChoiceAutoSchema: Schema<ToolChoiceAuto> = object({
  type: ['type', type8EnumSchema],
});
