/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema } from '../schema';
import { Type9Enum, type9EnumSchema } from './type9Enum';

export interface ToolChoiceAny {
  type: Type9Enum;
}

export const toolChoiceAnySchema: Schema<ToolChoiceAny> = object({
  type: ['type', type9EnumSchema],
});
