/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, object, optional, Schema, string } from '../schema';
import { CacheControl, cacheControlSchema } from './cacheControl';
import { InputSchema, inputSchemaSchema } from './inputSchema';

export interface Tool {
  name: string;
  /**
   * Description of what this tool does.
   *  Tool descriptions should be as detailed as possible. The more information that the model has about what the tool is and how to use it, the better it will perform. You can use natural language descriptions to reinforce important aspects of the tool input JSON schema.
   */
  description?: string;
  inputSchema: InputSchema;
  cacheControl?: CacheControl | null;
}

export const toolSchema: Schema<Tool> = object({
  name: ['name', string()],
  description: ['description', optional(string())],
  inputSchema: ['input_schema', lazy(() => inputSchemaSchema)],
  cacheControl: [
    'cache_control',
    optional(nullable(lazy(() => cacheControlSchema))),
  ],
});
