/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { CacheControl, cacheControlSchema } from './cacheControl';
import { Type5Enum, type5EnumSchema } from './type5Enum';

export interface ToolResultContent {
  type: Type5Enum;
  toolUseId: string;
  isError?: boolean;
  content?: string;
  cacheControl?: CacheControl | null;
}

export const toolResultContentSchema: Schema<ToolResultContent> = object({
  type: ['type', type5EnumSchema],
  toolUseId: ['tool_use_id', string()],
  isError: ['is_error', optional(boolean())],
  content: ['content', optional(string())],
  cacheControl: [
    'cache_control',
    optional(nullable(lazy(() => cacheControlSchema))),
  ],
});
