/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import { Type10Enum, type10EnumSchema } from './type10Enum';

export interface ToolChoiceTool {
  type: Type10Enum;
  /** The name of the tool to use */
  name: string;
}

export const toolChoiceToolSchema: Schema<ToolChoiceTool> = object({
  type: ['type', type10EnumSchema],
  name: ['name', string()],
});
