/**
 * Artifical Intelligence APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string, unknown } from '../schema';
import { Type4Enum, type4EnumSchema } from './type4Enum';

export interface ToolUseContentResponse {
  type: Type4Enum;
  id: string;
  name: string;
  input?: unknown;
}

export const toolUseContentResponseSchema: Schema<ToolUseContentResponse> = object(
  {
    type: ['type', type4EnumSchema],
    id: ['id', string()],
    name: ['name', string()],
    input: ['input', optional(unknown())],
  }
);
